### ISSUE TITLE
Mapping of results to terms used in the paper

### ISSUE THREAD

**Issue by paulaberry** [jszavits/NEAR#4]
I have installed and run NEAR on some Ribo-Seq and RNA-Seq datasets with interesting results. I have a question about how to interpret those results, and exactly what the outputs map to in the paper published in Nucleic Acids Research.

Note that the line where the column IDs are specified in ReadMe.md are missing `omega` and `omega0`, so I am assuming they are columns 7 and 8, respectively, as the others are in the same order as in the list following.

* Is `omega` in the outputs the same as alpha or kappa in the paper, or is there another parameter in the paper it is equivalent to? I could not find a specific mention of a result assigned to omega in the paper or the supplemental information.
* Is 'current' equivalent to J in the paper, or J/alpha?
* I am finding that the initial outputs (ie, `rho0`, `omega0`, and `current0`) are much more strongly correlated to my features of interest than the "main" results of `rho`, `omega`, and `current`. My understanding is that the initial outputs are only taking into account the one measurement at that specific codon, while the "optimized" outputs are the results when a model is found that is most reasonable for the entire transcript. Am I correct in my understanding?

**Comment by jszavits** [comment]
Hi Paula,

I am terribly sorry that your message somehow slipped under my radar. If this is still of any relevance to you now, here are the answers to your questions:

- `omega` is `kappa` in our paper, i.e. the ratio between the true elongation rate and the initiation rate
- `current` is equivalent to J/alpha in the paper.
- This is interesting. `rho0`, `omega0` and `current0` are initial guesses which assume no or very low ribosome traffic on the mRNA. The program then computes better estimates `omega` and `current` that take into account the traffic. So you are absolutely right, the optimised values take into account possible correlations between ribosomes due to collisions and therefore are optimised for the entire transcript, while the initial guess assumes no such correlations.

**Comment by jszavits** [comment]
This issue has been explained.
