### ISSUE TITLE
Reccomendations to calculate input data

### ISSUE THREAD

**Issue by FranziMe** [jszavits/NEAR#5]
Hi,

I would love to work with your tool. I managed to install and run your example just fine. 
Currently I am struggling with making my own input data. I have Riboseq and RNAseq data from c.elegans.
I work in a bioinformatics corefacility so time for experimenting around to get the right input data is limited. 

Would you perhaps please have some recommendation of tools you used to get the A-site counts. 
Any help is gratefully appreciated! 

Best wishes,
Franzi

**Comment by jszavits** [comment]
Hi Franzi,

thank you for getting in touch. If I understand you correctly, you have the raw Riboseq and RNAseq data? I recommend using riboviz (https://github.com/riboviz), a software developed at Edinburgh where I work, which is a pipeline for getting A-site counts from the raw data. I encourage you to get in touch with the people involved in riboviz, as they would be happy to help you with the data processing.

Once you get the A-site counts from the raw data, there is another issue of how to normalise the data so that instead of A-site counts you get A-site density. This is tricky because you need to know exactly how many ribosomes were in the experiment per each mRNA species. You said you have RNA-seq data, so that could be used as a proxy, but bare in mind that RNA-seq does not give you absolute RNA numbers unless you have something to normalise it such as RNA spike-ins.

Hope that helps and best wishes
Juraj

**Comment by FranziMe** [comment]
Hi Juraj,

Thank you for your reply!
I was able to get the input data and somewhat estimate the ribosome density. It's running fine for most of my samples. 

I did notice that some samples already failed with the following error:

```
At line 318 of file NEAR.f90
Fortran runtime error: Attempting to allocate already allocated variable 'positions'

Error termination. Backtrace:
#0  0x7f757aba88da
#1  0x7f757aba9395
#2  0x7f757aba973a
#3  0x55e0e1a7797a
#4  0x55e0e1a7b558
#5  0x7f757a80f09a
#6  0x55e0e1a70279
#7  0xffffffffffffffff

```
Do you know where this might come from? Or what I can check in my data to fix it. I am not very experienced in fortran.

On a positive note the program finished successfully for some of my other samples :)

Best wishes,
Franzi

**Comment by jszavits** [comment]
This last error has been fixed.

**Comment by jszavits** [comment]
This issue has been fixed.
